"""Cache Service — manages pre-scored transaction data.

Loads scored_transactions.parquet at startup and serves it from memory.
This keeps GET /transactions at <50ms with no live ML computation.

The parquet file is generated by scripts/build_shap_cache.py and contains
every test transaction pre-scored with SHAP + human explanations.
"""

from __future__ import annotations

import json
import time
from pathlib import Path

import pandas as pd
import structlog

from app.core.config import Settings
from app.core.exceptions import CacheNotReadyError
from app.schemas.response_schemas import (
    ExplanationFactor,
    HumanExplanation,
    ModelStatsData,
    ConfusionMatrix,
    TransactionRecord,
)
from app.schemas.shap_schemas import SHAPFeature

logger = structlog.get_logger(__name__)


class CacheService:
    """Manages in-memory caches for transactions, global SHAP, and model stats."""

    def __init__(self, settings: Settings) -> None:
        self._settings = settings
        self._transactions: list[dict] = []
        self._model_stats: ModelStatsData | None = None
        self._is_ready = False

    # ── Loading ────────────────────────────────────────────────────────────

    def load(self) -> None:
        """Load all caches from disk. Called once at app startup."""
        self._load_transactions()
        self._load_model_stats()
        self._is_ready = True
        logger.info(
            "Cache loaded",
            transactions=len(self._transactions),
            model_stats_loaded=self._model_stats is not None,
        )

    def _load_transactions(self) -> None:
        path = self._settings.scored_transactions_path

        if not path.exists():
            logger.warning(
                "Scored transactions file not found — GET /transactions will return empty. "
                "Run scripts/build_shap_cache.py to generate it.",
                path=str(path),
            )
            self._transactions = []
            return

        t0 = time.perf_counter()
        df = pd.read_parquet(path)
        elapsed = (time.perf_counter() - t0) * 1000

        # Limit to cache_size rows (keep highest risk first)
        if "risk_score" in df.columns:
            df = df.sort_values("risk_score", ascending=False)

        df = df.head(self._settings.transactions_cache_size)
        self._transactions = df.to_dict(orient="records")

        logger.info(
            "Transaction cache loaded",
            rows=len(self._transactions),
            latency_ms=round(elapsed, 1),
        )

    def _load_model_stats(self) -> None:
        path = self._settings.model_stats_path

        if not path.exists():
            logger.warning(
                "model_stats.json not found — GET /model-stats will use defaults.",
                path=str(path),
            )
            self._model_stats = _default_model_stats()
            return

        with path.open("r", encoding="utf-8") as f:
            raw: dict = json.load(f)

        try:
            cm = raw.get("confusion_matrix", {})
            self._model_stats = ModelStatsData(
                model_version=raw.get("model_version", "mock-1.0"),
                accuracy=raw.get("accuracy", 0.0),
                precision=raw.get("precision", 0.0),
                recall=raw.get("recall", 0.0),
                f1_score=raw.get("f1_score", 0.0),
                auprc=raw.get("auprc", 0.0),
                false_positive_rate=raw.get("false_positive_rate", 0.0),
                false_negative_rate=raw.get("false_negative_rate", 0.0),
                confusion_matrix=ConfusionMatrix(
                    true_negatives=cm.get("tn", 0),
                    false_positives=cm.get("fp", 0),
                    false_negatives=cm.get("fn", 0),
                    true_positives=cm.get("tp", 0),
                ),
                training_samples=raw.get("training_samples", 0),
                fraud_samples=raw.get("fraud_samples", 0),
                legitimate_samples=raw.get("legitimate_samples", 0),
                fraud_rate_percent=raw.get("fraud_rate_percent", 0.0),
            )
        except Exception as exc:
            logger.error("Failed to parse model_stats.json", error=str(exc))
            self._model_stats = _default_model_stats()

    # ── Query API ─────────────────────────────────────────────────────────

    def get_transactions(
        self,
        page: int = 1,
        page_size: int = 50,
        sort: str = "risk_desc",
        min_risk: float | None = None,
        fraud_only: bool = False,
    ) -> tuple[list[dict], int]:
        """Return a paginated, filtered, sorted slice of the transaction cache.

        Returns:
            (records, total_count) tuple.
        """
        self._assert_ready()

        rows = list(self._transactions)

        if fraud_only:
            rows = [r for r in rows if r.get("classification") == "fraud"]

        if min_risk is not None:
            rows = [r for r in rows if r.get("risk_score", 0) >= min_risk]

        # Sorting
        sort_map = {
            "risk_desc":   ("risk_score",  True),
            "risk_asc":    ("risk_score",  False),
            "time_desc":   ("timestamp",   True),
            "amount_desc": ("amount",      True),
        }
        sort_key, reverse = sort_map.get(sort, ("risk_score", True))
        rows.sort(key=lambda r: r.get(sort_key, 0), reverse=reverse)

        total = len(rows)
        start = (page - 1) * page_size
        end = start + page_size

        return rows[start:end], total

    def get_model_stats(self) -> ModelStatsData:
        """Return model performance statistics."""
        self._assert_ready()
        return self._model_stats  # type: ignore[return-value]

    # ── Internal ───────────────────────────────────────────────────────────

    def _assert_ready(self) -> None:
        if not self._is_ready:
            raise CacheNotReadyError("Cache is still loading. Retry in a moment.")

    @property
    def is_ready(self) -> bool:
        return self._is_ready

    @property
    def transaction_count(self) -> int:
        return len(self._transactions)


# ---------------------------------------------------------------------------
# Default model stats (used when model_stats.json is missing)
# ---------------------------------------------------------------------------

def _default_model_stats() -> ModelStatsData:
    """Return placeholder stats when the real stats file isn't available yet."""
    return ModelStatsData(
        model_version="mock-1.0 (awaiting real model from teammate)",
        accuracy=0.972,
        precision=0.921,
        recall=0.873,
        f1_score=0.896,
        auprc=0.862,
        false_positive_rate=0.018,
        false_negative_rate=0.127,
        confusion_matrix=ConfusionMatrix(
            true_negatives=279500,
            false_positives=5305,
            false_negatives=58,
            true_positives=434,
        ),
        training_samples=227846,
        fraud_samples=385,
        legitimate_samples=227461,
        fraud_rate_percent=0.17,
    )
